### PR TITLE
Full refresh of model decorations on Frame edit 

### PR DESCRIPTION
**Pull request by aymanhab**
Make sure to update components that are "connected-to" rather than only those "owned" by a Frame

Fixes issue #1340

### Brief summary of changes
When a Frame location/orientation are edited, refresh all model decorations rather than only subcomponents or owned components since there are other components that are connected to Frames via sockets (e.g. IMU)
  
### Testing I've completed
Tested model/change in issue #1340 

### CHANGELOG.md (choose one)
- updated...

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong ready to test

**Comment by aymanhab** [comment]
@jenhicks or @nickbianco if you can test it would be great since @carmichaelong is out. Thank you

**Comment by carmichaelong** [comment]
@aymanhab LGTM. Tested the Windows 10 artifact. IMU visualization changed for updates to both Translation and Rotation

**Comment by aymanhab** [comment]
Thanks @carmichaelong 👍

**Pull request merged**
