### PR TITLE
Update Confluence URLS for 4.1

### PR DESCRIPTION
**Pull request by jimmyDunne**
Update confluence links to use https, remove port numbers, and use generic confluence (rather than specific OpenSim40).

### CODE REVIEW

**Comment by jenhicks** [comment]
The links should still include the OpenSim40 reference. This will point people to the correct version of the documentation when we release another major increment with a new confluence space (e.g., OpenSim 5.).

**Comment by jenhicks** [comment]
There is currently a redirect that points OpenSim40 -> OpenSim. With a 5.0 release, we would remove this redirect and change links in the GUI to OpenSim50 -> OpenSim.

**Comment by jimmyDunne** [comment]
Thanks, @jenhicks. I reverted it.

**Comment by jenhicks** [comment]
Thanks ... changes look good.

**Comment by aymanhab** [comment]
@jenhicks This PR now has both the welcome page and links update (Thanks @jimmyDunne). Let's see if we get an artifact from the PR that we can use to verify. Splash screen not included yet

**Comment by aymanhab** [comment]
To test updated URLs use artifacts from this PR

**Comment by jimmyDunne** [comment]
Tested the artifact and the URLs seem to work and go to the expected locations

**Comment by aymanhab** [comment]
Thanks @jimmyDunne Merging.

**Pull request merged**
