### PR TITLE
Remove motion displayer assemble

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
Remove call to model.assemble when playing back results from file (after calling formStateStorage)

### Testing I've completed
Bouncing-block FD and playback works fine and doesn't violate contacts/constraints

### CHANGELOG.md (choose one)

- no need to update because bugfix

### CODE REVIEW

**Comment by aymanhab** [comment]
Note that leg69 still shows patella totally off  without assemble but this is due to opensim-core issue https://github.com/opensim-org/opensim-core/issues/2240

**Comment by aymanhab** [comment]
@chrisdembia @aseth1 it would help test issue https://github.com/opensim-org/opensim-models/issues/87 if this was merged. Thoughts?

**Comment by chrisdembia** [comment]
Well now that you've created the PR, we have a build with which to test https://github.com/opensim-org/opensim-models/issues/87. Which should be merged first, this PR or https://github.com/opensim-org/opensim-models/issues/87?

I think we should merge this PR no matter what, because leaving in the assemble can cause erroneous playback.

**Comment by aymanhab** [comment]
I agree, and it will make it clear if more models/motions need motionType fix.

**Comment by chrisdembia** [comment]
Perhaps we can discuss with @aseth1 in the stand-up.

**Comment by aymanhab** [comment]
@chrisdembia I think we can merge this based on the verbal agreement in scrum meeting, will wait for your formal review/approval.

**Comment by aymanhab** [comment]
Thank you @chrisdembia 👍

**Pull request merged**
