### PR TITLE
Fix edit wrap geometry

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #844

### Brief summary of changes
Edits of parameters of analytical shapes requires recreation of geometry. This was not done for wrapObjects and ContactGeometry.

### Testing I've completed
Loaded models, modified paramaters, transforms and quadrants of wrapObjects and ContactSpheres and all worked as expected.

### CHANGELOG.md (choose one)

- no need to update because bugfix

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia Do you know why builds are failing on ci?

**Comment by aymanhab** [comment]
Appveyor claims conflicts can't be resolved somehow while travis can build! Trying to follow the steps suggested by github to resolve conflicts resulted in accidental merge of branch!

**Comment by chrisdembia** [comment]
Let me know if you want some git help here.

**Comment by aymanhab** [comment]
Thanks @chrisdembia I would have preferred another pair of eyes check a build with the fix before it goes into master but couldn't get a windows build on the PR branch. It's a relatively small change so we can modify/update as needed. We'll have a build on Windows, Mac to test  #844 #346 soon.

**Pull request merged**
