### PR TITLE
[WIP] [appveyor] Prep for opensim-core-VC141

### PR DESCRIPTION
**Pull request by chrisdembia**
WIP; don't merge yet.

### CODE REVIEW

**Comment by chrisdembia** [comment]
Now that https://github.com/opensim-org/opensim-core/pull/2070 is merged, we can wait until master build of those changes is complete, and we can restart the tests for this PR.

**Comment by chrisdembia** [comment]
@aymanhab AppVeyor is failing because of the Java bindings are out of sync:

```
[nb-javac] C:\projects\opensim-gui\Gui\opensim\modeling\src\org\opensim\modeling\OutputSpatialVec.java:15: error: cannot find symbol
   [nb-javac]     super(opensimCommonJNI.OutputSpatialVec_SWIGUpcast(cPtr), cMemoryOwn);
   [nb-javac]                           ^
   [nb-javac]   symbol:   method OutputSpatialVec_SWIGUpcast(long)
   [nb-javac]   location: class opensimCommonJNI
   [nb-javac] C:\projects\opensim-gui\Gui\opensim\modeling\src\org\opensim\modeling\OutputSpatialVec.java:31: error: cannot find symbol
   [nb-javac]         opensimCommonJNI.delete_OutputSpatialVec(swigCPtr);
   [nb-javac]                         ^
   [nb-javac]   symbol:   method delete_OutputSpatialVec(long)
   [nb-javac]   location: class opensimCommonJNI
   [nb-javac] C:\projects\opensim-gui\Gui\opensim\modeling\src\org\opensim\modeling\OutputSpatialVec.java:39: error: cannot find symbol
   [nb-javac]     this(opensimCommonJNI.new_OutputSpatialVec__SWIG_0(), true);
   [nb-javac]                          ^
   [nb-javac]   symbol:   method new_OutputSpatialVec__SWIG_0()
   [nb-javac]   location: class opensimCommonJNI

```

I wonder if this is related to the OutputReporter crash.

Could you fix this?

**Comment by aymanhab** [comment]
PR opened. I don't think this is related to OutputReporter crash. When you're out of sync, functions are not found which throws exceptions on loading rather than crash intermittently. That would be my guess.

**Comment by chrisdembia** [comment]
I just restarted the `travis-ci/pr` build.

**Comment by chrisdembia** [comment]
This PR is ready to be merged. The appveyor/branch failure is because the change from #503 is not incorporated in this branch (but is included in master).

**Comment by aymanhab** [comment]
@chrisdembia is this ready to merge?

**Comment by chrisdembia** [comment]
> @chrisdembia is this ready to merge?

Yes. I merged master into this branch and the tests pass.

**Pull request merged**
