### PR TITLE
Make set as component

### PR DESCRIPTION
**Pull request by aseth1**
Fixes issue #483 

### Brief summary of changes
GUI code changes to accommodate `ModelComponentSet` recognized as and deriving from `ModelComponent` from https://github.com/opensim-org/opensim-core/pull/2285.

### Testing I've completed
Was able to build GUI locally and load models and run Tools. More thorough testing is required.

### CHANGELOG.md (choose one)
- no need to update because pathnames are new 4.0

### CODE REVIEW

**Comment by aseth1** [comment]
@aymanhab or @chrisdembia how do I update the version of the feed source (L54) to another appveyor build of core or do I need to somehow push PR build on core to the feed location (not edit L54)?
https://github.com/opensim-org/opensim-gui/blob/ac2e2f63e5604af68721d65834df42c325bed479/appveyor.yml#L51-L56

**Comment by chrisdembia** [comment]
> @aymanhab or @chrisdembia how do I update the version of the feed source (L54) to another appveyor build of core or do I need to somehow push PR build on core to the feed location (not edit L54)?

Yes, I think the easiest way to handle this is to temporarily push PR builds for opensim-core. I've tried to create a new NuGet package `opensim-core-VC141-sets`. See https://github.com/opensim-org/opensim-core/pull/2306

We will also need to update this GUI branch to pull this new package once https://github.com/opensim-org/opensim-core/pull/2306 is merged.

**Comment by chrisdembia** [comment]
I've created #1006, which should be merged into this PR.

**Comment by chrisdembia** [comment]
I haven't been able to get AppVeyor to create a build using the opensim-core `sets` build :(

**Comment by chrisdembia** [comment]
@aymanhab I undid the changes to `appveyor.yml`.

**Comment by aymanhab** [comment]
Thanks @chrisdembia I think this needs to wait for opensim-core master to build and then will be tested. I noticed opensim-models module is out of date so we need to fix that, once build is successful we can merge. Thanks again @chrisdembia 🥇

**Pull request merged**
