### PR TITLE
Leave experimental data alone when cleaning up motion objects 

### PR DESCRIPTION
**Pull request by aymanhab**
Leave experimental data alone upon motion change

Fixes issue #1168

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by aymanhab** [comment]
@tkuchida Would you have a chance to check this has been fixed in this PR artifact? Thank you

**Comment by tkuchida** [comment]
The Issue that was raised in #1168 has been fixed. Minor note: The muscles change color after clicking Poses -> Default (see below). Not sure why… presumably the location of a light is being updated, but it seems like this type of update should occur when the model gets the focus back (i.e. after double-clicking "arm26" in the Navigator) rather than when Poses -> Default is clicked.

Before clicking Poses -> Default | After clicking Poses -> Default
--- | ---
image-before | image-after

**Comment by aymanhab** [comment]
Muscle changing color when state is changed since 4.0 e.g. by manually changing coordinates is expected behavior, otherwise you have inconsistent muscle colors and coordinates.

**Comment by aymanhab** [comment]
Thanks for testing @tkuchida

**Pull request merged**
