### PR TITLE
Make model marker less shiny

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #1107
### Brief summary of changes
Change material specification of model markers to match those of experimental markers for consistency. Along with opensim-core fix to scale factors these two fixes combined result in better looking model markers.
### Testing I've completed

Created new markers, loaded models with markers and inspected visualization

### CHANGELOG.md (choose one)
-updated

### CODE REVIEW

**Comment by aymanhab** [comment]
@jimmyDunne If you review and merge will get an Artifact of the gui with integrated fix.

**Comment by jimmyDunne** [comment]
They are definitely different. I have a few comments just as impressions as I looked at it for the first time. 

From a not-so-far distance away, the markers appear more 'black' than pink. 
image

If I would have to guess, it may because the dark shading on the marker is on the superior surface of the maker, rather than than the infererior. The experimental markers seem to have the darker shading on the inferior surface of the sphere, which we may want to mimick. I think that would help the Model marker pinl coloring to stand out. 

image

**Comment by aymanhab** [comment]
James, the wrong shading suggest this build of the gui does not have the
core fix. I can restart the gui build to force that unless you locally
built latest master on both core and gui.

**Comment by jimmyDunne** [comment]
I don't build the GUI locally so if you could force another CI build I can get the artifact?

**Comment by aymanhab** [comment]
Thanks @jimmyDunne Artifact of master is ready to test. Sorry about the confusion

**Comment by jimmyDunne** [comment]
Yep, looks great! Thanks, Ayman. 
image

**Pull request merged**
