### PR TITLE
[WIP] [appveyor] Set userdir to include commit hash

### PR DESCRIPTION
**Pull request by chrisdembia**

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia Is this related to an open issue? Thanks

**Comment by chrisdembia** [comment]
Yes #416.

**Comment by chrisdembia** [comment]
CI failed because of the updates to opensim-core.

**Comment by aymanhab** [comment]
Thanks, after master finishes building you should be able to merge it into
this branch to get the build to pass, or let me know and I'll do it.

My understanding is that this applies only to ci, so if I build locally
(e.g. to modify icon etc. I still need to make this change manually, or
instead add a target in Ant to do it on demand) is that correct?

Thanks,
-Ayman

On Mon, Nov 6, 2017 at 4:00 PM, Christopher Dembia <notifications@github.com

**Comment by chrisdembia** [comment]
> My understanding is that this applies only to ci, so if I build locally
(e.g. to modify icon etc. I still need to make this change manually, or
instead add a target in Ant to do it on demand) is that correct?

Correct. We can make Ant do it instead.

**Comment by aymanhab** [comment]
Would be wonderful if this is done in Ant but not urgent. Will this PR need redoing then? If so I'll wait, otherwise will merge. Let me know @chrisdembia

**Comment by chrisdembia** [comment]
Okay I'll try doing this in Ant, eventually.

**Comment by aymanhab** [comment]
Wouldn't hurt to merge now due to low risk, changes only on ci. Merging

**Pull request merged**
