### PR TITLE
Implement heartbeat on timer to keep visualizer alive

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #523

### Brief summary of changes
When connecting to the visualizer, start a heartbeat ping signal every minute to keep the connection alive

### CHANGELOG.md (choose one)

- will update once verified fixed.

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco or @carmichaelong if you can test the artifact from this PR to see if visualization stops after idle for a while I'd appreciate it

**Comment by nickbianco** [comment]
@aymanhab, giving it a try now.

**Comment by aymanhab** [comment]
@nickbianco Thanks for testing, I'll merge per your feedback after ci completes

**Comment by aymanhab** [comment]
same failures as main branch so unrelated. Merging

**Pull request merged**
