### PR TITLE
Call assemble after setStateVariableValues to satisfy constraints

### PR DESCRIPTION
**Pull request by aymanhab**
Address issue #617

### CODE REVIEW

**Comment by aymanhab** [comment]
Looking for feedback on:
- If states file should contain constrained coordinates (so other code using this e.g. in tools doesn't ned to assemble)
- If we call assemble only in cases where the model contains constraints
- If this interacts with the fix to issue #540

**Comment by aseth1** [comment]
@aymanhab  are these changes in latest sourceforge GUI download?

**Comment by aseth1** [comment]
AFAICT #617 was not fixed in OpenSim 85d9741-2018-03-22. I still see the patella in space.

**Comment by aymanhab** [comment]
No, they're just on a branch PR, if they look ok to you I can merge them.

**Comment by aymanhab** [comment]
Local build with the fix shows patella in right place as expected.
Retested model and motion from 540 and they were still displaying correctly. 
Waiting for review or suggested optimizations if any

**Comment by aseth1** [comment]
I believe the fix will work and will not break #540.

**Comment by aseth1** [comment]
@aymanhab yes, if you just verified, then go ahead and merge.

**Comment by aymanhab** [comment]
Thanks @aseth1 we should have the build from ci shortly, or you can pull the GUI master

**Pull request merged**
