### PR TITLE
Fix external force applies force

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #1153

### Brief summary of changes
When the user unchecks the "Applies Force" checkbox, the ForceIDentifier and selected Force columns are blanked so that the internal "appliesForce" method returns false and the flag is persistent. This is the most surgical fix since it affects only rarely used scenarios without needing to change much of the functionality, documentation, or surprise users with changes to dialogs.

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by sebastianskejoe** [comment]
Might also want to add similar logic when the user unchecks the applies torque checkbox. Otherwise it seems like a good fix.

**Comment by aymanhab** [comment]
Build with fix available [here](https://ci.appveyor.com/project/opensim-org/opensim-gui/builds/29000434/artifacts) to verify the fix on windows. Thanks @sebastianskejoe

**Comment by sebastianskejoe** [comment]
Works on Windows 10. Thanks!

**Comment by aymanhab** [comment]
Thanks for testing @sebastianskejoe 👍 
Can you do a quick review @chrisdembia ?

**Comment by aymanhab** [comment]
@chrisdembia this should be rather quick, thank you

**Comment by aymanhab** [comment]
Thanks @chrisdembia and @sebastianskejoe

**Pull request merged**
