### PR TITLE
Welcome page, Doxygen link and splash screen

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by carmichaelong** [comment]
Thanks @aymanhab, looks good. Just one question on the doxygen link since it doesn't exist yet. What's the normal order for changing that link and updating doxygen? Might be confusing for some users testing the beta if the doxygen link doesn't exist before it gets released.

**Comment by aymanhab** [comment]
Good point, we ask Henry to upload/update separately. I'll send him the zip
file now but we need the most recent since the new Moco classes need to be
there.

**Comment by aymanhab** [comment]
It exists now thanks to Henry, let me know if you approve merging. Thank you

**Review by carmichaelong — APPROVED** [review]

**Comment by aymanhab** [comment]
Thanks @carmichaelong

**Pull request merged**
