### PR TITLE
Remove stale refs to kinematics_for_external_loads property

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0
### Brief summary of changes
Remove property lookup for removed Properties related to external_loads kinematics

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong I ran into this while troubleshooting issue #1229

**Comment by carmichaelong** [comment]
@aymanhab I found some of the files in the GUI repo by doing a search. Those results are at the end of the thread at #1221. Hope that helps get you started on this issue

**Comment by aymanhab** [comment]
Thanks @carmichaelong this PR takes care of the only instance where the removed property was used. The rest are configuration/setup files. Not sure if you're suggesting we update these as well in this PR.

**Comment by carmichaelong** [comment]
Just wanted to point it out, but I agree that it's not critical for this PR. The list would also indicate that this is the only one that should have any user-facing effect, so this is by far the most important of the 4 checkboxes.

**Comment by carmichaelong** [comment]
Just tested and looks to fix the issue with the red bubble popping up about the external loads property. One thing I noticed was that the warning about the removal of the property didn't show up, though, is this expected?

**Comment by aymanhab** [comment]
Thanks @carmichaelong I went ahead and removed all the remaining references even in comments so all checkboxes on the GUI repo are now handled.

**Comment by aymanhab** [comment]
@carmichaelong Please let me know if you approve this PR so I can move it off my plate. Thank you

**Review by carmichaelong — APPROVED** [review]

**Comment by carmichaelong** [comment]
@aymanhab Sorry about that, the email from your ping just got into my inbox even though it was timestamped for 6 hours ago(?!). LGTM

**Comment by aymanhab** [comment]
Thanks @carmichaelong 👍

**Pull request merged**
