### PR TITLE
Latest updates from master of opensim-models repo

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
Bring fixes from opensim-models repo to opensim-gui. In particular leg39 model, update StrengthOfSimulaion tutorial files for motionType

### CHANGELOG.md (choose one)

- no need to update because internal
- updated...

### CODE REVIEW

**Comment by nickbianco** [comment]
Cool. All these changes have been reviewed/merged in the models repo? Not sure if I need to review anything here.

**Comment by chrisdembia** [comment]
I think we can merge this once the tests pass.

**Comment by aymanhab** [comment]
Tests passed, this can be merged or we can test the artifact from the PR build to make sure the files are properly installed so we can update before merging.

**Comment by chrisdembia** [comment]
Tested locally on Mac and all looks good. Merging.

**Pull request merged**
