### PR TITLE
Popup model loading errors

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #483 partially
### Brief summary of changes
If Model loading error log is not empty then popup a Warning dialog with the error messages. This is checked only on Model loading and need the log to be populated on the opensim-core side.

### Testing I've completed
Loaded multiple models and got no Popup, Will test more and check formatting when log is populated.

### CHANGELOG.md (choose one)

- no need to update because this is new functionality

### CODE REVIEW

**Comment by aseth1** [comment]
Applied this PR to https://github.com/opensim-org/opensim-core/pull/2243. Additional changes were required to append to the validation log within `Model::finalizeProperties()` which causes the same message to be written to the messages windows (which could be OK) and appears in the console repeatedly when using the API an `finalizeFromProperties()` is invoked during model editing.

The validationLog mechanism is currently unable to present warnings or errors raised during finalizing connections or initializing the `System` and/or its `State`.

Below is the popup that appears:
https://github.com/opensim-org/opensim-core/pull/2243
image

**Comment by tkuchida** [comment]
I think some users might find that message cryptic. "Please consider updating… to ensure consistent unit conversion…" is ambiguous: are units converted sometimes but not always ("ensure")? Perhaps tell them (1) what could go wrong, (2) how they would detect a malfunction, and (3) what to do if a malfunction occurs.

**Comment by aseth1** [comment]
> Perhaps tell them (1) what could go wrong, (2) how they would detect a malfunction, and (3) what to do if a malfunction occurs.

(1) Coordinate values for `Coupled` coordinates can be assigned values that are in degrees if a coordinate was were previously (pre-4.0) labeled as `Rotational`
(2) This will lead to incorrect motion of bodies governed by the `Coupled` coordinate when playing back a pre-4.0 motion file, and produce erroneous velocity and acceleration estimates that yield incorrect inverse-dynamics and static-optimization results
(3) Apply the `updateKinematicsFilesForUpdatedModel(model_file, list_of_MOT_files)` utility to update motion files generated prior to 4.0, which will undo the conversion of `Coupled` coordinates to degrees so that they are consistent with the 4.0 model.

Let me know if this sounds reasonable. Please feel free to polish, reword in manner you feel will be more easily interpreted by users and I'll update the message in https://github.com/opensim-org/opensim-core/pull/2243.

**Comment by aseth1** [comment]
Current message ready for review in: https://github.com/opensim-org/opensim-core/pull/2264

**Comment by aseth1** [comment]
The *validationLog* log mechanism as implemented by `Model` is not sufficient to relay messages generated by `Component`s of the `Model`.  As it stands a `Component` is able to complain (throw an `Exception`) if its properties are invalid and in its `extendFinalizeFromProperties` it throws or handles them but there is not mechanism to write to a common *validationLog* and certainly no way to get access to the Model's log.

In the case of duplicates they are renamed automatically and we can write a message to the console, but the Model's validation log is not accessible by the `Component`. `Component` is not and should not be aware of concrete types so I rejected the idea of traversing up the ownership tree to get the `Model` to append to its log. 

Pushing *validationLog* down to `Component` is possible but then the issue is handling the fact that every `Component` has a log and composing them is not trivial (and a potential waste).  We could make *validationLog* a singleton shared by all `Component`s. Then the same log can be accessed by different components, which may not be desirable. 

@aymanhab @chrisdembia @tkuchida how would you like the messaging to work (at first)? @aymanhab i think your intention was to keep it very simple and have a direct way for Model to relay warnings to users during loading, but it seems to me we might want to control what bubbles up to users and what doesn't based on a warning/messaging level, and in that case it seems what is in place will not work.

This reminds me of discussions in https://github.com/opensim-org/opensim-core/issues/36. Perhaps we can leverage an existing mechanism.

**Comment by aymanhab** [comment]
@aseth1 While the hierarchical model/component layout is great for distributing responsibility for development purposes, the model is the most common object that reads from file from a user persepctive and so it makes sense for it to be the only object responsible for reporting file parsing/handling-old-format errors, that's why the validationLog lives with the model. 

Having individual components throw errors/excpetions to the outside world would be problematic because in general components maybe too low level to know the context. if they throw exceptions I think these need to be caught and reported by the model  (in the validationLog or whatever final mechanism we decide on). It may be possible when reading from old file format to do two passes, the first one is what we do today, if that results in any errors/exceptions, a check/validate pass is performed  that returns detailed errors/warnings. the validation log could be passed along from the model for that second pass.

**Comment by aymanhab** [comment]
@aseth1 I updated the branch to show html capable dialog now, you can give it a spin and let me know how it goes. Although you can't follow the links the user will be able to copy the URLs and paste into the browser, also some minor formatting support.

**Comment by aseth1** [comment]
I don't think the message window has improved with the latest change:

image

Newlines are ignored so spacing is not great, looks like an editable form and it also remains editable.

**Comment by aymanhab** [comment]
@aseth1 Sure I can help make this better. Keep in mind that since this is html now that new lines are ignored and the formatting would need to use <br> instead but you get to use other html as well for bold etc. if it helps.

**Comment by aseth1** [comment]
@aymanhab I think I prefer the look (not the text) of the previous popup error window. We can ask @jenhicks @tkuchida @chrisdembia  for their preference.

**Comment by scrum2a** [comment]
In scrum, we agreed to go back to original warning dialog.

**Comment by aymanhab** [comment]
Last commit reverted, should have the standard warning dialog back at head of branch @aseth1

**Comment by chrisdembia** [comment]
> @aymanhab @chrisdembia @tkuchida how would you like the messaging to work (at first)?

I'm fine with each component having a *validationLog*.

**Comment by chrisdembia** [comment]
I'm not merging this yet because of @aseth1's discussion about the *validationLog* mechanism.

**Comment by aymanhab** [comment]
@chrisdembia As of now validationLog lives with the model because it is intended to capture model loading errors. One problem with having it live with Component is that it would live long post construction which is unnecessary, and even for programmatically created components. It may actually make sense to tie it to the XMLDocument to limit this lifetime, and pass it along to parsing and post-parsing validation.
- It's important that in the most common case we have a simple test to check for errors/warnings in one place rather than try to assemble a long list of mostly empty error logs to figure out if something went wrong.

**Comment by chrisdembia** [comment]
Those are good points. We should see what other software packages do. I don't think we should address the bigger validationLog issue now though.

**Comment by scrum2a** [comment]
@aseth1 please respond about `validationLog`.

**Comment by aymanhab** [comment]
Based on discussion with @aseth1 at Sprint planning I think we agreed this can be merged and the discussion moved to separate issue to address a more general mechanism for communicating errors/warnings at component level. Can you please confirm, @chrisdembia Thanks

**Pull request merged**
