### PR TITLE
Turn off recording accelerations when using Kinematics analysis in GUI

### PR DESCRIPTION
**Pull request by aymanhab**
When using kinematics internally to record states, no need to compute accelerations or realize higher then velocity.

### CODE REVIEW

**Comment by chrisdembia** [comment]
This would seem to be a change in behavior; users may have expected to get accelerations from RRA and now will not. My preference is to call `realizeAcceleration()` within the Kinematics reporter.  In fact, even with this PR, there would be a bug in opensim-core.

**Comment by chrisdembia** [comment]
If this kinematics analysis is only used internally by the GUI (this isn't the kinematics analysis added by RRA/CMC to print kinematics STO files?), then this change is good. However, a bug likely still remains in opensim-core.

**Comment by aymanhab** [comment]
Thanks for the quick turnaround @chrisdembia Yes this kinematics analysis is used to create the animations when running tools in the GUI so there's no user expectation of accelerations.

**Comment by aseth1** [comment]
@aymanhab IMHO the GUI should no longer be using Analyses internally. Use the `StatesTrajectory` and `StatesTrajectoryReporter` for all/any recording and playback of states. Analyses should remain only for user legacy reasons.

**Pull request merged**
