### PR TITLE
Update comments to refer to main branch instead of master

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #1429 

### Brief summary of changes
Change build system files to create 4.5 version in development

### CHANGELOG.md (choose one)

- no need to update because internal

### CODE REVIEW

**Review by carmichaelong — APPROVED** [review]

**Comment by carmichaelong** [comment]
@aymanhab actually, I did a quick skim of the code with a search. Technically out of the scope of the name of this PR, but you may want to also check here: https://github.com/opensim-org/opensim-gui/blob/2b18792903889dec4a025ff2f293508c330c0e03/.gitmodules#L4

**Comment by luisgizirian** [comment]
#1419 . Build script looks for a 'master' branch even it's 'main' now. I've just tried the Linux script, so I'm not sure about the rest.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @luisgizirian, thank you for noticing this issue in the build scripts. I have just updated it.

**Comment by aymanhab** [comment]
Thanks for reporting and for the review @carmichaelong I went ahead and removed the unused OpenSimAPI submodule so we're good with that.

**Comment by luisgizirian** [comment]
@AlbertoCasasOrtiz, looks like wiki docs needs to reflect the change. 

> https://github.com/opensim-org/opensim-gui/wiki/Build-Instructions#configuration-1 (4. For Developers...)

**Comment by aymanhab** [comment]
Thanks @luisgizirian for keeping an eye on this, much appreciated  👍

**Pull request merged**
