### PR TITLE
Bring fix to movie capture and default snapshot quality from threejs

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #895 and maybe #299

### Brief summary of changes
Two fixes in threejs repo are brought over:
-  Use different encoder and higher frame rate for movie capture
- Make snap_shot quality slider correspond correctly to value used internally so at least low res grab is possible

### Testing I've completed
More frames and smoother movies for model/motions in issue #895, resolution of png files captured map to quality slider as expected.

### CHANGELOG.md 

- no need to update because bugfix

### CODE REVIEW

**Comment by aymanhab** [comment]
@aseth1 you can try the new movie encoding in this PR and let me know what you see. Also the build has the fix to the snapshot quality slider, so at least you should be able to get un-cropped snapshots at low slider setting

**Comment by aymanhab** [comment]
There's the issue 895 model and data files which was particularly short (0.15 sec.) I deally for a few models/motions of reasonable length we can check the length of playback time to see if it maps reasonably close to realtime (e.g. 2 sec, played at a speed of .1 produces roughly 20 sec of smooth motion etc.)

**Comment by aseth1** [comment]
The artifact for this PR OpenSim_9551139f-2018-08-02 does not have the *snapshot quality slider* and the snapshot feature seems to be disabled.

image

**Comment by aseth1** [comment]
As for video/movie recording it does seem better than I can capture 0.25s of motion at 0.1s playback and it occupies about 4s of movie time. However it includes about 1s of time for me to click from the 🎥 to the ⏯ buttons and then back to the 🎥 to stop recording. I don't think the video should be recording when there is no motion. Also it is impossible to discern if the video camera is in record mode. In 3.3 we had an orange highlight. Could we have some change in the icon or highlighting to indicate that recording is on?

**Comment by aymanhab** [comment]
Thanks for the testing @aseth1 Can you check if the snapshot slider opens if you open the artifact for the second time (if you still have it around)? I'll undo that change to snapshot anyway so as to get the other fix to master and in the hands of more users. The behavior of when to start/stop recording should be the same as 3.3 though not optimal. When selected the background turns gray but that doesn't help with gray background, please open an issue and will try solutions.

**Comment by aymanhab** [comment]
I undid the snapshot change just in case, if anybody can try the Artifact and confirm snapshot button/slider is available then will merge and move to verified on Windows. Thanks

**Comment by aseth1** [comment]
Using the same artifact on Windows OpenSim_9551139f-2018-08-02 with the slider now present I can generate snapshots and quality 1 (556KB) and 2 (1602KB) and at 3 (3,049KB) and 4 (5952KB) the zoom changes and the view model get cutoff.
Original Screen Grab (365KB):
image

At quality 2:
opensim_snapshot_2

At quality 4:
opensim_snapshot_4

Hard to see without downloading the image and zooming, in but some of the muscles in front of the ankle (e.g. *per_tert_r*) do not appear clearly but only have strips drawn (this happens at all qualities, but not in the direct screen capture).

**Pull request merged**
