### PR TITLE
Last frame was missing from tools because step() is not called

### PR DESCRIPTION
**Pull request by aymanhab**
Change in core caused Step not to be called on last frame, instead end is called. Update the animation (analysis) on GUI side to follow this convention.

### CODE REVIEW

**Comment by aymanhab** [comment]
Address issue #511

**Comment by aseth1** [comment]
@aymanhab AFAICT in core, calling `Analysis::end(s)` is sufficient to record the final state correctly. In no instances are we calling `step(s)` in `end(s)`. Therefore if your `Analysis` is calling `processStep(s, N)` (e.g. `step(s, N)`)  in `end(s)` it is definitely inconsistent with Analyses in the API.  If you look at all the `end(s)` implementations they just call `record(s)` as does `step(s)` so I can see why you are needing to call `processStep()` which is likely is the recording guts. I would rename it `record(s)` and have your `step()` and `end()` call it. Then it will at least be consistent with the `Analyses` in core.

There was also an inconsistency between the `AnalyzeTool` and `ForwardTool` (Manager) and this was resolved by only calling `step(s)` during our march through states in `AnalyzeTool::run()` and integration and only `end(s)`, when reaching the last index of input data (`AnalyzeTool`) or finished integrating in the case of the `Manager`, and never `step(s)` and `end(s)` together.

**Comment by aymanhab** [comment]
@aseth1 thanks for the pointers as to why the behavior was changed. The "Analysis" being modified here is what records the kinematics or states so that they can be played back when tools are running. Since all these tools are "Analysis" based, the GUI follows suit (internally using StatesReporter or KinematicsReporter)  both of these invoke record (which is not part of the interface by the way) inside their end method. The GUI based Analysis uses the signature that takes a step number of "step" so that it can report progress. Please let me know if you have any further questions or concerns regarding this change.

**Comment by aseth1** [comment]
@aymanhab I know `record(s)` is not part of the public interface. The problem is that the public virtual methods `begin(s)`, `step(s, N)` and `end(s)` all have to do the same operation of recording something plus doing something else (like initialize Storage or finalize something). I do not like or approve of this interface - it is what it is. It appears that `record(s)` was invented to support the common operation that all three public methods have to do.

I think it safest moving forward to use a similar structure and not call `step(s)` or in your case `processStep(s)` inside of `end(s)` because if anything has to be added to `step()` you will inadvertently also bake it into `end(s)`. I am not saying that is happening, it just exposes your code to that risk and that may be hard to track down and debug in the future. 5 min know could save the team hours or even days hunting months and years down the road.

**Comment by aymanhab** [comment]
Thanks for the feedback @aseth1 I made a change to delegate the call to end(s) in the GUI Analysis to the corresponding end(s), and checked that results files saved in GUI have correct final frame and that it shows exactly once. Please let me know if you have any further concerns.

**Comment by aymanhab** [comment]
Thanks @aseth1 Merging since build failures on travis are due to sourceforge issues.

**Pull request merged**
