### PR TITLE
include fix to visualizer toolbar buttons

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #1147 

### Brief summary of changes
Visualizer was trying to find Model object by name to compute bounding box, replaced with more robust search by uuid which is better maintained.
### Testing I've completed
Buttons performed as expected in local build

### CHANGELOG.md (choose one)

- no need to update because bug was not reproducible in public releases.

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia or @jimmyDunne If you can test the artifact that would be great. Thank you

**Comment by aymanhab** [comment]
Anybody else to test so we can merge? @jenhicks @nickbianco @tkuchida

**Comment by chrisdembia** [comment]
I'll test.

**Comment by chrisdembia** [comment]
Works for me on Mac 10.15.

**Comment by aymanhab** [comment]
Thanks @chrisdembia

**Pull request merged**
