### PR TITLE
update threejs repo

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
When recording movies, and user starts playback, restart recording

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong @nickbianco @jenhicks The artifact from this PR fixes the issue where recording starts on push rather than on play animation. Also this has a fix for issue #1216 
I now have a fix to change formats so that animations can be stored as Frames (png, jpg), as of now this is customizable from the scripting shell (for testing purposes). Would love to have this PR merged first, as well as get feedback on entry points for configuration (visualizer controls dropdown vs. scripting shell).

**Comment by aymanhab** [comment]
@antoinefalisse if interested..

**Comment by carmichaelong** [comment]
Two issues here look fixed (OpenSim 4.2-2020-10-23-c635110 on Windows 10):
1) Recording starts on user playback (does not end until video button hit again)
2) Directional views work

LGTM

**Comment by aymanhab** [comment]
Thanks @carmichaelong 👍

**Pull request merged**
