### PR TITLE
Fix place where  pathpoints are shown when not engaged.

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #1111

### Brief summary of changes
Path visualization now keeps track of all wrap-pathpoints that are engaged so it can decide what to do when a wrap-object becomes disengaged.

### Testing I've completed
Loaded model reported on forum and in issue 1111 and moved sliders, loaded motions, all displayed correctly.

### CHANGELOG.md (choose one)

- no need to update because rare scenario to reproduce, issue fix could be included

### CODE REVIEW

**Comment by aymanhab** [comment]
@jenhicks @jimmyDunne suggested fix works for Apoorva's model but breaks two muscles in our Shoulder model, investigating a more robust fix before passing to others to test.

**Comment by aymanhab** [comment]
@jimmyDunne I believe I have this issue fixed along with #2569 would be good to give it a good spin, especially for muscles with models with multiple wrapping (Apoorva's , Arm26 and Shoulder model) as well as the files in issue reports once a GUI build is available. Thank you

**Comment by aymanhab** [comment]
James, to test if you have the right build load Apoorva's model and load the motion attached here
[bad_gas.txt](https://github.com/opensim-org/opensim-gui/files/3688178/bad_gas.txt) if gaslat and gasmed show correctly in first from then you have the correct build otherwise you don't.

**Comment by jimmyDunne** [comment]
Seems to show the expected behavior on opening 🍾 
image

**Pull request merged**
