### PR TITLE
Associate scaled model with file in same folder as input model 

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #1182 

### Brief summary of changes
Associate the scaled model with a file (_scaled.osim) in the same folder as original model so that custom geometry is located using same mechanism as original model.

### Testing I've completed
Loaded Wu shoulder model and scaled it (manually) and got expected visualization.

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by aymanhab** [comment]
Build failure on osx is unrelated (jdk version issue). Things to test:
- Scale models with custom geometry (e.g. Wu shoulder or Rajagopal)
- Check what happens if assumed file name (originalmodel)_scaled.osim already exists.
- Try model with ContactMesh since these used to have even bigger problems with scaling

**Comment by aymanhab** [comment]
scaled model is not saved on its own, the new suggested name is good, but if file exists, it's overwritten without warning which is unrelated issue. IF model is saved in different folder problem recurs. scaled model with contact mesh without issue. Ready for review/testing @carmichaelong

**Comment by carmichaelong** [comment]
I like that it's a small fix, but I'm trying to understand how this works exactly. Will this change some working directory downstream by changing the inputfilename? If so, how much more code would need to be in place to separately change the working directory without making a placeholder file name?

**Comment by aymanhab** [comment]
@carmichaelong This doesn't change any working directory, it just tells the scaled model that its current filename is "originalmodelpath/model_scaled.osim", this affects the behavior of the code but not the file system at all. When user decides to save scaled model, it's saved to the suggested file, if user wants to pick different file name they can choose saveAs. If they change folder they'll run into problem downstream because Geometry will not be found but that's unrelated to GUI opertion.

**Comment by carmichaelong** [comment]
Tested with OpenSim-4.2-2020-03-29-4fedac9a on Win10 Pro.

Confirmed scaling Rajagopal model on 4.1 distribution led to geometry issue. Artifact here does not have that issue. This PR LGTM. Might be good to have another more general issue about how to best handle Geometry files/folder.

**Comment by aymanhab** [comment]
Thanks @carmichaelong 👍 
I think issue #1078 is a duplicate or related as well. Feel free to create an issue to start discussion on how to best handle this, ideally model is a zip file with embedded meshes but that comes with a price.

**Comment by carmichaelong** [comment]
That issue looks good, thanks for digging that up. Feel free to merge.

**Comment by aymanhab** [comment]
Thanks @carmichaelong much appreciated. Merging

**Pull request merged**
