### PR TITLE
[WIP] Try xcode9.3 as claimed to use java 1.8 by default (https://docs.trav…

### PR DESCRIPTION
**Pull request by aymanhab**
…is-ci.com/user/reference/osx/#OS-X-Version)

Fixes issue #<issue_number>

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia Per the travis page here https://docs.travis-ci.com/user/reference/osx using xcode9.3 would get java 1.8 by default, however the build fails due to trying to use open-jdk 13, any idea what we're doing wrong here? Thanks

**Comment by chrisdembia** [comment]
Well, it looks like Travis-CI is failing because it can't find Ant, and GitHub Actions is failing because `brew install ant` is not working (probably temporarily).

**Comment by aymanhab** [comment]
@chrisdembia True but not finding ant is a downstream effect of not finding the right java, per the page I linked to above their osx, xcode combination defaults to xcode 9.4.1 which is java 13.  Check log of last successful build shows Java 1.8 installed first

**Comment by chrisdembia** [comment]
Hmmm...maybe we could try specifying the `jdk` key.

https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks

**Pull request closed without merging**
