### PR TITLE
Use latest threejs and jxbrowser repositories

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

This is the same as https://github.com/opensim-org/opensim-gui/pull/1317 but using updated repositories for threejs and visualizer/jxbrowser
### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by aymanhab** [comment]
Build artifacts here just in case
https://github.com/opensim-org/opensim-gui/actions/runs/1408849557
@jenhicks @carmichaelong @nickbianco @antoinefalisse

**Comment by aymanhab** [comment]
@jenhicks @carmichaelong Any reason not to merge this PR? Thanks

**Comment by carmichaelong** [comment]
@aymanhab I downloaded the artifact from this new PR to double check, and the visualizer window doesn't show anything when I try to load a model (it's just all white and doesn't have the drop down for "Open View Controls" in the top right)

**Comment by aymanhab** [comment]
Please download the build of master branch since this PR is old and was
subsumed by another one that was merged based on our discussion yesterday.

**Comment by carmichaelong** [comment]
Thanks for the heads up, definitely didn't notice the merge of another PR with all of these other ones open. Visualizer shows up again with the nightly build of master branch.

**Pull request closed without merging**
