### PR TITLE
Update SWIG bindings per API change 032718

### PR DESCRIPTION
**Pull request by aymanhab**
Update bindings to latest API on core

### CODE REVIEW

**Comment by aymanhab** [comment]
@chrisdembia Is there a reason the constructProperty_xx macros produce public methods? Are these usable from scripting? Any fundamental reason on the core side that these are not protected or private (so they don't pollute the interface for scripting)? Thanks

**Comment by chrisdembia** [comment]
> Is there a reason the constructProperty_xx macros produce public methods? 

Not really, but it could be helpful when/if we allow creating components in scripting.

> Any fundamental reason on the core side that these are not protected or private (so they don't pollute the interface for scripting)?

I don't think these macros can safely use the visibility keywords, because the macro doesn't know what section it's in.

**Comment by aymanhab** [comment]
Thanks @chrisdembia for the clarification. While the macro can't tell the context, the class writer/header can and should handle this properly so as not to pollute the public interface and methods searched in both Doxygen and by Scripting. I don't think this is needed even for extension from Scripting which would use the swig/director and keep its own internals rather than use the Maco-centric Property system.

**Comment by chrisdembia** [comment]
> the class writer/header can and should handle this properly so as not to pollute the public interface and methods searched in both Doxygen and by Scripting.

The macro contains functions that *should* be public, though.

**Comment by aymanhab** [comment]
Thanks for the feedback @chrisdembia I opened issue #2135 [https://github.com/opensim-org/opensim-core/issues/2135] to track.

**Pull request merged**
