### PR TITLE
Use OpenSimContext setLocation method

### PR DESCRIPTION
**Pull request by aymanhab**
Properly edit GeometryPath point location and recreate the system, also refresh path display on edit/undo.

Fixes issue #816

### Brief summary of changes
In the past, graphical editing of pathpoint called set_location directly on the pathpoint which is incomplete since Path cache entry and system underneath weren't updated. This PR (along with opensim-core https://github.com/opensim-org/opensim-core/pull/2234) fixes this by making the right call sequence when doing graphical editing consistent with how it's done in path edit dialog.

### Testing I've completed
Can move pathpoints on GeometryPaths with wrapping and undo the changes

### CHANGELOG.md (choose one)

- no need to update because bugfix

### CODE REVIEW

**Comment by aymanhab** [comment]
This is WIP pending merging the opensim-core side of the fix since it uses it, builds will fail till then.

**Comment by chrisdembia** [comment]
@aymanhab thanks for your comment in https://github.com/opensim-org/opensim-core/pull/2234 but I still don't understand how this fixes #816. I suppose I will wait until I can test this locally.

**Comment by chrisdembia** [comment]
> In the past, graphical editing of pathpoint called set_location directly on the pathpoint which is incomplete since Path cache entry and system underneath weren't updated. This PR (along with opensim-core opensim-org/opensim-core#2234) fixes this by making the right call sequence when doing graphical editing consistent with how it's done in path edit dialog.

Does this cause the visualization to be updated as soon as a user graphically moves a path point?

**Comment by aymanhab** [comment]
@chrisdembia you should be able to test visual editing and undo for muscles including wrap objects. While path remains "goofy" during dragging, one done, path should restore to expected and same with undo. Please let me know if you can test this out. Thank you.

**Comment by chrisdembia** [comment]
Verified on Mac: can properly undo edits to path points.

aug-02-2018 17-25-39


Does this also address #928 ?

**Comment by aymanhab** [comment]
Thanks much @chrisdembia I believe it does address issue #928 as well

**Pull request merged**
