### PR TITLE
Updated deprecated environments in CI.

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Fixes issue #1388

### Brief summary of changes

Updated environment versions for Mac and Ubuntu to latest.

### Testing I've completed

Running CI job.

### CHANGELOG.md (choose one)

- no need to update because this is a CI matter.

### CODE REVIEW

**Comment by aymanhab** [comment]
While it would be good to have builds with latest versions, there're deeper issues that need to be addressed on opensim-core side first (e.g. https://github.com/opensim-org/opensim-core/pull/3295).
Also, since we build our distributions on github and users may not have the latest environment according to github we need actions to continue building with lowest supported os versions available on github as well (e.g. Windows 2019, Osx-11 and ubuntu 20).

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab As we talked about this morning, I have set the Ubuntu version and the MacOs version to the lowest versions supported by GitHub Actions.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz We need to check that the built application launches correctly without setting LD_LIBRARY_PATH or DYLD_LIBRARY_PATH on osx, otherwise we need to go back and fix since the application installer doesn't set these and asking users to do it is highly not recommended.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I just checked and the generated artifact is throwing the "Failed to load one or more dynamic libraries" error for: libgcc_s.1.1.dylib.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz that's why we need to go back to simtk-core and fix the cmake hacks described here https://github.com/opensim-org/opensim-gui/pull/1387

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab Looks like I didn't set the correct syntax for powershell/windows in CI for these lines:

https://github.com/opensim-org/opensim-gui/blob/bebac6984b17d84bc2dddb5e5fe452d51ae9f8f2/.github/workflows/continuous-integration.yml#L49

https://github.com/opensim-org/opensim-gui/blob/69c163606aa532e7751426eeb21ee02b874b599e/.github/workflows/continuous-integration.yml#L92

https://github.com/opensim-org/opensim-gui/blob/bebac6984b17d84bc2dddb5e5fe452d51ae9f8f2/.github/workflows/continuous-integration.yml#L131

I'd change it, but I'd prefer not to modify CI while you are working on it to avoid merging conflicts. Could you change `$GITHUB_ENV` by `$env:GITHUB_ENV`, and `$GITHUB_OUTPUT` by `$env:GITHUB_OUTPUT` in those lines, please?

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I think we can close without merging since the current CI is working properly

**Comment by aymanhab** [comment]
Agreed, Thanks @AlbertoCasasOrtiz

**Pull request closed without merging**
