### PR TITLE
Tweak imu tools ui

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
Change text on dialogs and menus to use IMU Placement (instead of Calibration), removed reference to "Sensor".

### Testing I've completed
Tested running the Opensense example from new setup and data files

### CHANGELOG.md (choose one)

- no need to update because not in production yet

### CODE REVIEW

**Comment by aymanhab** [comment]
This PR can be reviewed as is, a separate PR for models repo is updating the files for the example. Can be merged separately.
@carmichaelong @jenhicks

**Comment by carmichaelong** [comment]
Adding tag to link this to #1236. Looks like most points were addressed. One new issue and one old issue below:

- Noticed an issue with this branch's artifact when loading the IMU Placer xml file. The window resizes and cuts off text (that wasn't cut off before loading the file):
Before:
image
After:
image
- Probably lost in some of the thread from the issue was a slight wording change to the Data Transformation sections in IMU Placer and IMU IK: 
> Description of "sensor_to_opensim_rotations" could be the same with the GUI description too. Perhaps: "Space fixed Euler angles (XYZ order) from IMU space to OpenSim space" (this would be for both calibration and IMU IK)

**Comment by aymanhab** [comment]
Dialog fixed per feedback. Thanks for the review @carmichaelong

**Comment by carmichaelong** [comment]
Thanks @aymanhab, just tested and this looks good to me

**Review by carmichaelong — APPROVED** [review]

**Comment by aymanhab** [comment]
Thanks much @carmichaelong 🥇

**Pull request merged**
