### PR TITLE
Tool Help URLs to 4.0 Docs

### PR DESCRIPTION
**Pull request by jimmyDunne**
Fixes issue #900

### Brief summary of changes
Changed URL to point to 4.0 Docs

### Testing I've completed
URLS go to the correct locations

### CODE REVIEW

**Comment by jenhicks** [comment]
Thanks @jimmyDunne 

The links look right. Two comments:

- We should probably do a search of the GUI code to make sure there aren't any other OpenSim30 links floating around. Is that possible @aymanhab 
- The code is still doing a check to see if the user is online and trying to send to a local copy if the user is not online. For these pages, we are not distributing a local copy, so we may need to remove or update the code accordingly.

**Comment by aymanhab** [comment]
captureopensim30
File names and line numbers shown. Good idea @jenhicks 
@jimmyDunne You should modify the code as isConnected() is set to true, and an empty page-not-found-notOnline page will show up.

**Comment by aymanhab** [comment]
Exactly.

**Comment by aymanhab** [comment]
@jimmyDunne The changes look good but the editor you used messed around with newlines/spaces causing artificially big diffs in some files. if you transplant the changes using a text editor that doesn't try to reformat that would be great, then we can merge this PR. Thank you.

The *JNI files are autogenerated so we need to make a change in opensim-core for this change but this is done in a separate repo/PR.

**Comment by chrisdembia** [comment]
@aymanhab you can use this link to view the diff without changes in whitespace: https://github.com/opensim-org/opensim-gui/pull/902/files?w=1

**Comment by aymanhab** [comment]
Thanks for the pointer @chrisdembia, I changed the diff options temporarily and that's how I figured the changes were good but still the reformatting would be inconsistent when editing these files later.

**Pull request merged**
