### PR TITLE
[appveyor] Run NSIS to create an installer.

### PR DESCRIPTION
**Pull request by chrisdembia**
This is a WIP to address #710.

### CODE REVIEW

**Comment by chrisdembia** [comment]
AppVeyor failed because of SWIG bindings.

**Comment by chrisdembia** [comment]
This PR produced the following installer: https://ci.appveyor.com/api/buildjobs/wqpr6v9fweitbgh4/artifacts/OpenSim-3dced78c-2018-05-07-win64.exe

**Comment by chrisdembia** [comment]
No longer WIP; ready for review.

**Comment by jimmyDunne** [comment]
Chirs, I tested the installer on a W10 machine and it worked great! There are some minor things but the overall aim of an automated installer build is great and I think we should merge this as is.

**Comment by aymanhab** [comment]
@chrisdembia LGTM, the changes are mostly upgrading the SWIG wrapping AFAIK Looks safe but I failed to download the installer. Will try again later. Could be an issue to try to download an .exe through a link for security purposes.

**Comment by aymanhab** [comment]
Was finally able to download and install. Looks great. Thanks @chrisdembia

**Comment by aymanhab** [comment]
Leaving branch in case you want to test other installer fixes @chrisdembia otherwise feel free to delete the branch.

**Comment by chrisdembia** [comment]
Great; thanks for merging.

**Pull request merged**
