### PR TITLE
Commit build_on_ubuntu.sh from @idhamari

### PR DESCRIPTION
**Pull request by chrisdembia**
In #939, @idhamari shared a build script for the GUI. I do not think we are ready to support Ubuntu but I thought it would be good to store his script in the repository for future reference. @idhamari is that okay with you?

### CODE REVIEW

**Comment by idhamari** [comment]
Sure it belongs to everyone!

**Comment by aymanhab** [comment]
Considering PR #1181 I think we can close this issue, or do we still this need merging this PR @chrisdembia ?

**Comment by chrisdembia** [comment]
I don't want us to lose this file, so I think we should still put it somewhere on the master branch, with whatever disclaimers are appropriate.

**Comment by aymanhab** [comment]
There's a new script now on the wiki by @AlbertoCasasOrtiz so this issue is completed, please open otherwise

**Pull request closed without merging**
