### PR TITLE
Latest updates to threejs module 04/30/18

### PR DESCRIPTION
**Pull request by aymanhab**
include fixes to interactions between 3d view and visualizer menu from threejs module

### CODE REVIEW

**Comment by aymanhab** [comment]
Fix issues  #624, #625, #648

**Comment by jimmyDunne** [comment]
@ayman, what behavior were you hoping to affect with this PR? I am testing this build (OpenSim-299aa4f3-2018-04-30.zip) and the backspace/delete button doens't work in the text box (#648).

**Comment by chrisdembia** [comment]
@jimmyDunne try using this build: https://ci.appveyor.com/api/buildjobs/67ks3w3eyq4oto2u/artifacts/OpenSim-ba958aac-2018-04-30_threejs_r91.zip

To test this fix, we aren't using the master build because we are using a change in the three.js repo that was not merged into master.

**Comment by aymanhab** [comment]
@jimmyDunne this upgrades threejs to latest version, main effect is no introduced new bugs/unexpected-behavior and more importantly that this supports older gfx cards so some windows machines that complained about webgl support should work now. @jenhicks had one such machine, if you have access to more please test that visualizer comes up. Thanks

**Comment by jimmyDunne** [comment]
Thanks for the clarification, Ayman. Then this PR doesn't directly fix issues #624, #625, #648. I have moved those back into in-progress since the issues still exist and this PR doesn't change them. Thanks.

**Pull request merged**
