### PR TITLE
Update bindings 110923

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #0

### Brief summary of changes
Rerun swig with latest opensim-core, inspect diffs

### CHANGELOG.md (choose one)

- no need to update because internal

### CODE REVIEW

**Comment by aymanhab** [comment]
@nickbianco This the GUI side and the latest Matlab interfaces to assess if your planned example scripts would work or if changes to the swig interface are needed.

**Comment by nickbianco** [comment]
@aymanhab this is a pretty big diff. Do you need a line-by-line review or a just a stamp of approval?

**Comment by aymanhab** [comment]
@nickbianco Stamp of approval except for new classes or classes that you care about for your example which should have a few extra methods or signatures changed.

**Review by nickbianco — APPROVED** [review]
All the new classes and methods LGTM. Didn't check syntax since that is autogenerated by SWIG.

**Comment by aymanhab** [comment]
Sounds great, thanks @nickbianco

**Pull request merged**
