### PR TITLE
[WIP] Fix appveyor build (setting JAVA_HOME).

### PR DESCRIPTION
**Pull request by chrisdembia**

### CODE REVIEW

**Comment by aymanhab** [comment]
Thanks @chrisdembia Is that because default install location of Java has changed on appveyor? Branch pr builds were passing but master wasn't I think

**Comment by chrisdembia** [comment]
Yes, Chocolatey updated jdk8 from 1.8.0_121 to 1.8.0_152. I'm hoping these changes will help us avoid disruptions the next time Chocolately updates jdk8.

I think even the PR builds are failing.

**Comment by aymanhab** [comment]
AppVeyor build still failing because can't find java

**Comment by aymanhab** [comment]
@chrisdembia This feels so painful and time consuming, maybe we can use the full path to java.exe instead of adding to the path? Thanks for all your work on this, appreciate it.

**Comment by chrisdembia** [comment]
Yes, pretty frustrating. Good idea, but it's Ant that is trying to use `java.exe`, not us. I'm not sure how to tell Ant what to do.

**Comment by aymanhab** [comment]
@chrisdembia one more thought, could it be permissions on java.exe (not executable)? The dir command earlier shows only "a" permission, is that expected? Just trying to get the automated build upagain. Thanks.

**Comment by chrisdembia** [comment]
@aymanhab ready for review! The root of the issue was a silly typo (`/bin/bin` instead of `/bin`).

**Comment by chrisdembia** [comment]
I didn't only fix the typo. I also removed the installation of java and ant, because AppVeyor provides java and NetBeans provides ant.

**Comment by aymanhab** [comment]
Awesome, thank you @chrisdembia  :+1: 💯 🎆

**Comment by aymanhab** [comment]
Merging since Appveyor passed and travis is unaffected.

**Comment by chrisdembia** [comment]
Thanks for merging.

**Pull request merged**
