### PR TITLE
Bring fixes from threejs repo to opensim-gui

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #164 followup
### Brief summary of changes
Change color of button while recording from gray to red

### Testing I've completed
Tried recording and observed button color

### CHANGELOG.md (choose one)

- not sure if button color is documented anywhere

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong this PR should have the threejs changes/updates for #346 verification as well

**Comment by aymanhab** [comment]
@jenhicks Do we have documentation of visualizer button colors/behavior to update?

**Comment by tkuchida** [comment]
> Do we have documentation of visualizer button colors/behavior to update?

Searched Confluence for "movie". [This page](https://simtk-confluence.stanford.edu/display/OpenSim/Taking+Snapshots+and+Making+Movies) says the following:

**Comment by aymanhab** [comment]
Thanks @tkuchida the page doesn't specify highlighting colors which is good but has stale info regarding AVI format and Camera commands that are not available anymore, I'll open a documentation issue so it doesn't fall through the cracks.

**Comment by aymanhab** [comment]
@tkuchida or @aseth1 Did you verify you get the distinct red button while recording using this PR artifact? Thank you.

**Comment by jenhicks** [comment]
There is an issue to update documentation about the new visualizer.

**Comment by carmichaelong** [comment]
Tests from #346 on W10 using this branch check out (I will not merge yet, though, as it looks like there are other discussion / checks to do first):

1. Brick
a) `half_lengths` changes visualize ✔️  
b) `quadrants` hidden ✔️ 
2. Ellipsoid
a) `radii` changes does not visualize ✔️ 
b) `quadrants` hidden ✔️ 
3. Sphere
a) `radius` changes visualize ✔️ 
b) `quadrants` hidden ✔️ 
4. Cylinder
a) `radius` and `half_height` changes visualize ✔️ 
b) `quadrants` hidden ✔️ 
5. Cone
a) `height` and `base_radius` changes visualize ✔️ 
b) `quadrants` hidden ✔️

**Comment by aymanhab** [comment]
Thanks @carmichaelong the fixes on this PR are unrelated to the discussion on quadrants and fix other issues that you tested so I'll merge this PR. Thank you

**Pull request merged**
