### PR TITLE
Retire mac 10.15 as no longer supported on github

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #<issue_number>

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz for your review

**Comment by AlbertoCasasOrtiz** [comment]
Everything looks good to me. I'll mark as reviewerd once CI finishes. Windows failed, but it has been failed for a while in the same place.

**Review by AlbertoCasasOrtiz — APPROVED** [review]
LGTM!

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz Will merge then fix windows separately

**Pull request merged**
