### PR TITLE
GitHub Actions: Install netbeans on Mac

### PR DESCRIPTION
**Pull request by chrisdembia**
### Brief summary of changes

- Fix installation of NetBeans on Mac.
- Miscellaneous cleanup and organization.

### CHANGELOG.md (choose one)

- no need to update because...not user-facing

### CODE REVIEW

**Comment by chrisdembia** [comment]
@aymanhab I think the issue is that NetBeans is finding JDK 14, not JDK 8.

**Comment by chrisdembia** [comment]
Ready for review.

**Comment by aymanhab** [comment]
@chrisdembia Do you think now is a good time to stop building on travis so we have one place to maintain?

**Comment by chrisdembia** [comment]
> @chrisdembia Do you think now is a good time to stop building on travis so we have one place to maintain?

As soon as the builds are green for all three OSes, then yes. It seems like this is indeed the case.

**Comment by chrisdembia** [comment]
@aymanhab I've gone ahead and turned off the Travis-CI and AppVeyor continuous integration. I suggest we leave the related CI scripts in the repo in case we want to fall back on these services.

**Comment by aymanhab** [comment]
Merged, thanks @chrisdembia

**Pull request merged**
