### PR TITLE
Refactor pathwrap display

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #1331 

### Brief summary of changes
Conditional path points which were not active caused problems because we didn't account for intermediate points created to account for path wrap on the same muscle.
 
### Testing I've completed
tested with provided model without an issue
### CHANGELOG.md (choose one)

- Will update once after other wrapping issues are resolved/addressed

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong @jenhicks 
This is ready for testing, would be great to have more eyes testing it. I've been looking for issues/problematic models including:
- issue #1331
- https://simtk.org/projects/arms_hand_model/ (By Wendy)
- https://simtk.org/projects/full_body (By Apoorva)
- https://github.com/johnjdavisiv/wrapping-error-reprex Bug report by John Davis 

Are you aware of any in discussion, forum or in tutorials that had issues with ConditionalPathPoints or muscle wrapping visualization?

**Comment by aymanhab** [comment]
Is that different from master branch build?

**Comment by carmichaelong** [comment]
Good question, just tested on the last nightly build and installer worked from that artifact

**Comment by aymanhab** [comment]
I restarted the osx build hoping this resolves the issue since the changes in this PR are in two java files that have no bearing whatsoever on the build process/tools. Will let you know when ready. Are you using the Rosetta setting on M1 or using an old mac? I assume it's the same environment used for testing latest build on master but there could be a mixup somehow 😕

**Comment by carmichaelong** [comment]
Sounds good. Yeah, same environment (Rosetta on M1, don't need to set flip any switches for it to automatically use it in this case)

**Comment by aymanhab** [comment]
On my admittedly old macbook pro running 10.15.7 I had no issues downloading installing and running the installer from the artifact. Can you retry @carmichaelong or @nickbianco if you have access to a mac? Thank you. 
GitHub environment has undergone minor upgrade few days ago (before master build) so that could be related.

**Comment by carmichaelong** [comment]
@aymanhab the installer worked for me this time. I guess something weird must have just happened when creating the artifact before

**Comment by aymanhab** [comment]
Awesome, thanks much @carmichaelong and Reed

**Comment by aymanhab** [comment]
Testing seems to show no ill effects of this fix and no issues. Muscle editing broke because of unrelated change in visualizer code that will be submitted in a separate PR.

**Pull request merged**
