### PR TITLE
Color by activation handle disabled muscles

### PR DESCRIPTION
**Pull request by aymanhab**
Fixes issue #1123
### Brief summary of changes
Modify color maps to color muscles with a special color outside blue-to-red spectrum to indicate disabled.
### Testing I've completed
Ran SO with disabled muscle, got correct behavior/coloring.

### CHANGELOG.md (choose one)

- no need to update because...
- updated...

### CODE REVIEW

**Comment by aymanhab** [comment]
@jimmyDunne you can test this. First run SO with some disabled muscles, then use "Color Muscles from File..." and pick activation from SO.

**Comment by jimmyDunne** [comment]
Thanks, Ayman. I download the latest artifact and installed on a Windows 10 VM. I ran Static Optimization with, and without, the soleus_r muscle enabled. 

During Static Optimization execution, when soleus_r _enabled_ was unchecked, the muscle was colored grey. Immediately at the end of Static Optimization, the muscles were colored blue, with the soleus being red. 

Screen Shot 2019-07-17 at 2 02 42 PM

When I moved the motion slider, the muscles switched to the colored states from Static Optimization, including the greyed out soleus

Screen Shot 2019-07-17 at 2 03 23 PM

All other times, the coloring was working great and seemed to be what we would expect. The Static Optimization output files did not include the soleus_r muscle and, when coloring muscles using an activation file, the soleus was greyed out. Seems to work great except for that one little glitch described above. 

Let me know if there is anything else I can check?

**Comment by aymanhab** [comment]
Thanks @jimmyDunne I think this is due to the GUI being caught in between rendering live results and coloring with results from file which may have been always there but became more obvious once we switched to colors outside the blue-red spectrum. Will let you know.

**Comment by aymanhab** [comment]
@jimmyDunne, what model, files did you use. I get similar glitches but that's because the time window for the SO result files are different from those of the motion. Thank you.

**Comment by aymanhab** [comment]
@jimmyDunne, please retry the build after this commit. Thanks for testing

**Comment by jimmyDunne** [comment]
@aymanhab. I downloaded, installed, and tested with the latest artifact. I above issue (incorrect color when SO has finished) seems to be fixed 🚀 

 I tested loading states again and it still is working great. LGTM 🥂

**Comment by aymanhab** [comment]
Awesome, thanks for testing.

**Pull request merged**
