### PR TITLE
Default scriptsPath to ResourcesDir/Code/GUI

### PR DESCRIPTION
**Pull request by aymanhab**
Also populate cascade menu from it as described in user guide

Fixes issue #955

### Brief summary of changes
getScriptsDir() was renamed to getScriptsPath() and wired to be initialized to the new location of Scripts <Resources>/Code/GUI

### Testing I've completed
Made installer locally and behaved as expected/described in User/Guide 
### CHANGELOG.md (choose one)

- no need to update because bugfix

### CODE REVIEW

**Comment by chrisdembia** [comment]
On Mac, `Scripts Path` is `null/Code/GUI/`

image

**Comment by aymanhab** [comment]
Thanks @chrisdembia it's likely an initialization order issue where the preference is set before the OpenSimResourcesDir is populated, which happens actually after the user selects a directory to copy resources. I'll look into this.

**Comment by aymanhab** [comment]
Issue addressed by moving initial setting along with InstallResources, this artifact should be good to test all the latest scripts merged by @jimmyDunne once build is ready.

**Comment by jimmyDunne** [comment]
Works great! Gives the correct path to scripts!

**Comment by chrisdembia** [comment]
@aymanhab what is the reason for changing the `Scripts` menu?

before:
image

after:
image

**Comment by chrisdembia** [comment]
The new menu organization seems redundant.

Also, on Mac, I am not getting a `Scripts Path` preference, even after running `defaults delete org.opensim.version40`, running `installResources()` and restarting the GUI:

image

**Comment by aymanhab** [comment]
Thanks for the catch @chrisdembia I missed the change in the menu and apparently @jimmyDunne didn't see it either, will revert the menu change to keep 3.3 layout.
The preference should show up if you allow the installer to copy the resources for you, not sure what happens if you cancel out since preferences on windows and osx are different. Once you see it you should be able to verify it's working as documented. Please let me know otherwise.

**Comment by aymanhab** [comment]
Sorry, I mean on first launch. You can delete the file we use to mark first
launch manually.

**Pull request merged**
